version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    volumes:
      - redis-data:/data

  embedding-service:
    build:
      context: .
      dockerfile: docker/services/Dockerfile.embedding
    volumes:
      - ./embedding-service:/app/embedding-service
      - ./common:/app/common
    ports:
      - "8001:8001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDIS_URL=redis://redis:6379/0
      - SKIP_SUPABASE=true
      - TESTING_MODE=true
      - LOG_LEVEL=DEBUG
      - PYTHONPATH=/app
      - PIP_NO_CACHE_DIR=1
    depends_on:
      redis:
        condition: service_healthy
    command: >
      sh -c "
        echo 'Instalando dependencias...' &&
        pip install -r requirements.txt &&
        echo 'Iniciando servicio de embeddings...' &&
        uvicorn embedding_service:app --host 0.0.0.0 --port 8001 --reload
      "

  ingestion-service:
    build:
      context: .
      dockerfile: docker/services/Dockerfile.ingestion
    volumes:
      - ./ingestion-service:/app/ingestion-service
      - ./common:/app/common
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDIS_URL=redis://redis:6379/0
      - EMBEDDING_SERVICE_URL=http://embedding-service:8001
      - SKIP_SUPABASE=true
      - TESTING_MODE=true
      - LOG_LEVEL=DEBUG
      - PYTHONPATH=/app
      - PIP_NO_CACHE_DIR=1
    depends_on:
      - embedding-service
    command: >
      sh -c "
        echo 'Esperando a que el servicio de embeddings esté disponible...' &&
        timeout 120 bash -c 'until curl -s http://embedding-service:8001/health; do sleep 2; done' &&
        echo 'Instalando dependencias...' &&
        pip install -r requirements.txt &&
        echo 'Iniciando servicio de ingestion...' &&
        uvicorn ingestion_service:app --host 0.0.0.0 --port 8000 --reload
      "

  query-service:
    build:
      context: .
      dockerfile: docker/services/Dockerfile.query
    volumes:
      - ./query-service:/app/query-service
      - ./common:/app/common
    ports:
      - "8002:8002"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDIS_URL=redis://redis:6379/0
      - EMBEDDING_SERVICE_URL=http://embedding-service:8001
      - SKIP_SUPABASE=true
      - TESTING_MODE=true
      - LOG_LEVEL=DEBUG
      - PYTHONPATH=/app
      - PIP_NO_CACHE_DIR=1
    depends_on:
      - embedding-service
    command: >
      sh -c "
        echo 'Esperando a que el servicio de embeddings esté disponible...' &&
        timeout 120 bash -c 'until curl -s http://embedding-service:8001/health; do sleep 2; done' &&
        echo 'Instalando dependencias...' &&
        pip install -r requirements.txt &&
        echo 'Iniciando servicio de consultas...' &&
        uvicorn query_service:app --host 0.0.0.0 --port 8002 --reload
      "

  agent-service:
    build:
      context: .
      dockerfile: docker/services/Dockerfile.agent
    volumes:
      - ./agent-service:/app/agent-service
      - ./common:/app/common
    ports:
      - "8003:8003"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDIS_URL=redis://redis:6379/0
      - EMBEDDING_SERVICE_URL=http://embedding-service:8001
      - QUERY_SERVICE_URL=http://query-service:8002
      - SKIP_SUPABASE=true
      - TESTING_MODE=true
      - LOG_LEVEL=DEBUG
      - PYTHONPATH=/app
      - PIP_NO_CACHE_DIR=1
    depends_on:
      - embedding-service
      - query-service
    command: >
      sh -c "
        echo 'Esperando a que los servicios estén disponibles...' &&
        timeout 120 bash -c 'until curl -s http://embedding-service:8001/health && curl -s http://query-service:8002/health; do sleep 2; done' &&
        echo 'Instalando dependencias...' &&
        pip install -r requirements.txt &&
        echo 'Iniciando servicio de agentes...' &&
        uvicorn agent_service:app --host 0.0.0.0 --port 8003 --reload
      "

volumes:
  redis-data:
