version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    volumes:
      - redis-data:/data

  embedding-service:
    build:
      context: .
      dockerfile: docker/services/Dockerfile.embedding
    volumes:
      - ./embedding-service:/app/embedding-service
      - ./common:/app/common
    ports:
      - "8001:8001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDIS_URL=redis://redis:6379/0
      - SKIP_SUPABASE=true
      - TESTING_MODE=true
      - LOG_LEVEL=DEBUG
      - PYTHONPATH=/app
      - PIP_NO_CACHE_DIR=1
    depends_on:
      redis:
        condition: service_healthy
    command: >
      sh -c "
        echo 'Instalando dependencias...' &&
        pip install -r requirements.txt &&
        echo 'Iniciando servicio de embeddings...' &&
        uvicorn embedding_service:app --host 0.0.0.0 --port 8001 --reload
      "

volumes:
  redis-data:
