version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    volumes:
      - redis-data:/data

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  embedding-service:
    build:
      context: .
      dockerfile: docker/services/Dockerfile.embedding
    ports:
      - "8001:8001"
    environment:
      # Variables de credenciales
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL:-https://example.supabase.co}
      - SUPABASE_KEY=${SUPABASE_KEY:-dummy-key-for-testing}
      
      # Variables de identificación del servicio
      - SERVICE_NAME=embedding-service
      
      # Variables de conexión con servicios
      - REDIS_URL=redis://redis:6379/0
      - OLLAMA_API_URL=http://ollama:11434
      
      # Variables de configuración multi-tenant
      - TENANT_ID=default
      - CONFIG_ENVIRONMENT=development
      - LOAD_CONFIG_FROM_SUPABASE=false
      
      # Variables de configuración general
      - LOG_LEVEL=INFO
      - USE_OLLAMA=true
    depends_on:
      - redis
      - ollama

  ingestion-service:
    build:
      context: .
      dockerfile: docker/services/Dockerfile.ingestion
    ports:
      - "8004:8004"
    environment:
      # Variables de credenciales
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL:-https://example.supabase.co}
      - SUPABASE_KEY=${SUPABASE_KEY:-dummy-key-for-testing}
      
      # Variables de identificación del servicio
      - SERVICE_NAME=ingestion-service
      
      # Variables de conexión con servicios
      - REDIS_URL=redis://redis:6379/0
      - EMBEDDING_SERVICE_URL=http://embedding-service:8001
      - OLLAMA_API_URL=http://ollama:11434
      
      # Variables de configuración multi-tenant
      - TENANT_ID=default
      - CONFIG_ENVIRONMENT=development
      - LOAD_CONFIG_FROM_SUPABASE=false
      
      # Variables de configuración general
      - LOG_LEVEL=INFO
      - USE_OLLAMA=true
    depends_on:
      - embedding-service
      - ollama

  query-service:
    build:
      context: .
      dockerfile: docker/services/Dockerfile.query
    ports:
      - "8002:8002"
    environment:
      # Variables de credenciales
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL:-https://example.supabase.co}
      - SUPABASE_KEY=${SUPABASE_KEY:-dummy-key-for-testing}
      
      # Variables de identificación del servicio
      - SERVICE_NAME=query-service
      
      # Variables de conexión con servicios
      - REDIS_URL=redis://redis:6379/0
      - EMBEDDING_SERVICE_URL=http://embedding-service:8001
      - OLLAMA_API_URL=http://ollama:11434
      
      # Variables de configuración multi-tenant
      - TENANT_ID=default
      - CONFIG_ENVIRONMENT=development
      - LOAD_CONFIG_FROM_SUPABASE=false
      
      # Variables de configuración general
      - LOG_LEVEL=INFO
      - USE_OLLAMA=true
      - DEFAULT_OLLAMA_MODEL=llama3
    depends_on:
      - embedding-service
      - ollama

  agent-service:
    build:
      context: .
      dockerfile: docker/services/Dockerfile.agent
    ports:
      - "8003:8003"
    environment:
      # Variables de credenciales
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL:-https://example.supabase.co}
      - SUPABASE_KEY=${SUPABASE_KEY:-dummy-key-for-testing}
      
      # Variables de identificación del servicio
      - SERVICE_NAME=agent-service
      
      # Variables de conexión con servicios
      - REDIS_URL=redis://redis:6379/0
      - EMBEDDING_SERVICE_URL=http://embedding-service:8001
      - QUERY_SERVICE_URL=http://query-service:8002
      - OLLAMA_API_URL=http://ollama:11434
      
      # Variables de configuración multi-tenant
      - TENANT_ID=default
      - CONFIG_ENVIRONMENT=development
      - LOAD_CONFIG_FROM_SUPABASE=false
      
      # Variables de configuración general
      - LOG_LEVEL=INFO
      - USE_OLLAMA=true
      - DEFAULT_OLLAMA_MODEL=llama3
    depends_on:
      - embedding-service
      - query-service
      - ollama

volumes:
  redis-data:
  ollama-data:
