# backend/server-llama/k8s/embeddings-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: embeddings-service
  labels:
    app: embeddings-service
spec:
  replicas: 3  # Cambiar según necesidades de escalado
  selector:
    matchLabels:
      app: embeddings-service
  template:
    metadata:
      labels:
        app: embeddings-service
    spec:
      containers:
      - name: embeddings-service
        image: linktree-ai/embeddings-service:latest
        ports:
        - containerPort: 8001
        env:
          - name: SUPABASE_URL
            valueFrom:
              secretKeyRef:
                name: api-secrets
                key: supabase-url
          - name: SUPABASE_KEY
            valueFrom:
              secretKeyRef:
                name: api-secrets
                key: supabase-key
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: api-secrets
                key: openai-api-key
          - name: REDIS_URL
            value: "redis://redis-service:6379/0"
          - name: SERVICE_NAME
            value: "embeddings-service"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: embeddings-service
spec:
  selector:
    app: embeddings-service
  ports:
  - port: 8001
    targetPort: 8001
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: embeddings-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: embeddings-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70